# $$Introdução:~SageMaker~e~ S3$$

### $$Conceito:$$


**AWS:**

A AWS (Amazon Web Services) é um serviço de computação em nuvem desenvolvido pela Amazon. Ela oferece mais de 200 serviços completos de data centers por todo o mundo.

O serviço fornece esses serviços tecnológicos sob demanda através da internet com pagamento conforme o consumo da empresa ou do usuário.

Alguns dos serviços, projetos e recursos oferecidos são focados em tecnologias de infraestruturas como:

- **Computação, Armazenamento e banco de dados, Machine learning, Inteligência artificial, Data lakes, Análises, Internet das coisas, entre outros**

-----------------------------------------------------------------------------------------------------------------------


### $$Serviços~Oferecidos:$$

**Amazon S3 - Simple Storage Service:**

O Amazon Simple Storage Service (Amazon S3) é um serviço de armazenamento de objetos que oferece escalabilidade, disponibilidade de dados, segurança e performance

Através do Amazon S3 você será capaz de armazenar grandes quantidades de dados e de arquivos, e também de recuperar. Além disso, você pode acessar os seus dados de qualquer local no mundo através de diversos dispositivos.

Você pode otimizar custos, organizar dados e configurar controles de acesso ajustados para atender a requisitos específicos de negócios, organizacionais e de conformidade.

- **Casos de uso:**

    - Construir um data lake - Armazenar dados
    - Faça o backup e a restauração de dados críticos
    - Arquive dados com o menor custo
    - Execute aplicações nativas da nuvem



-----------------------------------------------------------------------------------------------------------------------


**Amazon EC2 - Elastic Computing Cloud:**

O Amazon Elastic Compute Cloud (Amazon EC2) oferece uma capacidade de computação escalável na Nuvem da Amazon Web Services (AWS).

O uso do Amazon EC2 elimina a necessidade de investir em hardware inicialmente, portanto, você pode desenvolver e implantar aplicativos com mais rapidez.

É possível usar o Amazon EC2 para executar quantos servidores virtuais forem necessários, configurar a segurança e as redes e gerenciar o armazenamento. 

O Amazon EC2 permite aumentar ou reduzir a escala para lidar com alterações nos requisitos ou com picos em popularidade, reduzindo sua necessidade de prever o tráfego.


- **O Amazon EC2 fornece os seguintes recursos:**

    - Ambientes de computação virtual, conhecidos como instâncias
    - Os modelos pré-configurados para suas instâncias, conhecidos como Imagens de máquina da Amazon (AMIs)
    - Várias configurações de capacidade de CPU, memória, armazenamento e redes para suas instâncias
    - Informações seguras de login para suas instâncias usando pares de chave 
    - Volumes de armazenamento para dados temporários que são excluídos quando você interrompe, hiberna ou encerra sua instância
    - Um firewall que permite especificar os protocolos, portas e intervalos de IPs de origem
    - Metadados, conhecidos como tags, que você pode criar e atribuir aos recursos do Amazon EC2




-----------------------------------------------------------------------------------------------------------------------


**Amazon IAM - Identity And Access Management:**

O AWS Identity and Access Management (IAM) é um serviço da Web que ajuda você a controlar o acesso aos recursos da AWS de forma segura. Você usa o IAM para controlar quem é autenticado (fez login) e autorizado (tem permissões) a usar os recursos

- **Casos de uso:**

    - Aplique permissões refinadas e escale com controle de acesso baseado em atributos
    - Gerencie o acesso por conta ou escale o acesso em contas e aplicações da AWS
    - Estabeleça barreiras de proteção preventivas e em toda a organização na AWS
    - Defina, verifique e dimensione corretamente as permissões para alcançar o privilégio mínimo



-----------------------------------------------------------------------------------------------------------------------


**Amazon Sagemaker - IDE:**

O Amazon SageMaker é um serviço totalmente gerenciado que permite que desenvolvedores e cientistas de dados criem, treinem e implantem rápida e facilmente modelos de aprendizado de máquina em qualquer escala.

----------------------------------------------------------------------------------------------------------------------------


----------------------------------------------------------------------------------------------------------------------------

## $$Objetivo:$$

## $$Criar ~conexão ~com~AWS,~ Importar~ Exportar~ arquivos ~usando~ S3$$

----------------------------------------------------------------------------------------------------------------------------


----------------------------------------------------------------------------------------------------------------------------

In [49]:
#Importar Pacotes

#Faz a integração do AWS com a Linguagem Python
import boto3

#Pacote para Enviar os arquivos para o S3
from sagemaker.s3 import S3Uploader

In [65]:
# Conexão com AWS
session = boto3.Session()

**Cria uma sessão na AWS**

In [66]:
#Região do Datacenter
session.region_name

'sa-east-1'

**Verificar o nome da região do Datacenter da AWS**

In [52]:
#Criar uma sessão na s3
s3_client = session.client('s3')

**Cria uma sessão na s3 para armazenar os dados**

In [53]:
#Criar um bucket via codigo

#Nome da pasta
bucket_name ='armaz1'

#Localização do servidor
s3_location = {'LocationConstraint': 'sa-east-1'}

#Associar o Bucket com a região do datacenter da AWS
s3_client.create_bucket(Bucket=bucket_name,CreateBucketConfiguration=s3_location)

{'ResponseMetadata': {'RequestId': 'FQPPBRPCC4AE4V4M',
  'HostId': 'WGxnQOQJIKNc4YZiCihU9e8fIx5sfLGM/Bi0sIh0ZB2IJ4QGvlEDYqdQCi3d1C+NWC0vkLPhr+c=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'WGxnQOQJIKNc4YZiCihU9e8fIx5sfLGM/Bi0sIh0ZB2IJ4QGvlEDYqdQCi3d1C+NWC0vkLPhr+c=',
   'x-amz-request-id': 'FQPPBRPCC4AE4V4M',
   'date': 'Mon, 29 Aug 2022 19:53:58 GMT',
   'location': 'http://armaz1.s3.amazonaws.com/',
   'server': 'AmazonS3',
   'content-length': '0'},
  'RetryAttempts': 0},
 'Location': 'http://armaz1.s3.amazonaws.com/'}

**Criado o nome da pasta que será usado na s3**

## Enviar arquivos na s3

In [47]:
#Criar subpasta para armazenamento do arquivo
subpasta = 'arquivo_csv'

#Caminho da pasta
caminho = f's3://{bucket_name}/{subpasta}'
print(f'Link para acessar as pastas e arquivos: {caminho}')

Link para acessar as pastas e arquivos: s3://armaz1/arquivo_csv

**Caminho da pasta para armazenar os dados**

In [72]:
#Enviar arquivo para o s3
s3_arquivo = S3Uploader.upload('Introducao/house_prices.csv',caminho)
print(s3_arquivo)

s3://armaz1/arquivo_csv/house_prices.csv

**Pasta onde esta salvo o arquivo csv dentro da AWS**

## Fazer o Download de um arquivo na s3

In [73]:
# Acesso ao armazenamento s3
s3_resource = boto3.resource('s3')

**Variável de acesso ao s3**

In [98]:
#Download do arquivo

#Parametros da função: download_file
caminho_pasta = 'arquivo_csv/house_prices.csv'
novo_nome_arquivo = 'H_prices.csv'

#Fazer o download
s3_resource.Bucket(bucket_name).download_file(caminho_pasta,novo_nome_arquivo)

**Note que para fazer o download do arquivo primeiro precisa colocar o caminho da pasta e depois o novo nome do arquivo**

In [99]:
#Carregar dataset
import pandas as pd
pd.read_csv('H_prices.csv')

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

**Dataframe carregado após a importação do arquivo no S3**